# Preprocessing csv files

In [1]:
import numpy as np
import pandas as pd

## Load Data

In [2]:
filename = "14.08.01-08.07.xlsx.xlsx"
new_filename = "a-14.08.01-08.07.csv"

In [3]:
train = pd.read_excel("futures_data/" + filename)
train.head()

,2014년 08월 07일(목),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,일별 박스오피스 검색 리스트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,순위,영화명,개봉일,매출액,매출액,매출액증감,매출액증감율,누적매출액,관객수,관객수증감,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
3,NaN,NaN,NaN,NaN,점유율,(전일대비),(전일대비),NaN,NaN,(전일대비),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,명량,2014-07-30 00:00:00,4892511700,0.595,-380933700,-0.1,61033902816,652776,-50111,...,1239,6776,한국,한국,(주)빅스톤픽쳐스,씨제이이앤엠(주),15세이상관람가,"사극,액션",김한민,"최민식,류승룡,조진웅,김명곤,진구,이정현,권율,노민우,김태훈,이승준,오타니 료헤이,..."

## Preprocessing Excel files

In [4]:
new_colums = ['순위',
              '영화명',
              '개봉일',
              '매출액',
              '매출액 점유율',
              '매출액증감 (전일대비)',
              '매출액증감율 (전일대비)',
              '누적매출액',
              '관객수',
              '관객수증감 (전일대비)',
              '관객수증감율 (전일대비)',
              '누적관객수',
              '스크린수',
              '상영횟수',
              '대표국적',
              '국적',
              '제작사',
              '배급사',
              '등급',
              '장르',
              '감독',
              '배우'
             ]

In [5]:
train.columns = new_colums
train.head()

,순위,영화명,개봉일,매출액,매출액 점유율,매출액증감 (전일대비),매출액증감율 (전일대비),누적매출액,관객수,관객수증감 (전일대비),...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,일별 박스오피스 검색 리스트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,순위,영화명,개봉일,매출액,매출액,매출액증감,매출액증감율,누적매출액,관객수,관객수증감,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
3,NaN,NaN,NaN,NaN,점유율,(전일대비),(전일대비),NaN,NaN,(전일대비),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,명량,2014-07-30 00:00:00,4892511700,0.595,-380933700,-0.1,61033902816,652776,-50111,...,1239,6776,한국,한국,(주)빅스톤픽쳐스,씨제이이앤엠(주),15세이상관람가,"사극,액션",김한민,"최민식,류승룡,조진웅,김명곤,진구,이정현,권율,노민우,김태훈,이승준,오타니 료헤이,..."

In [6]:
train = train.dropna(how='all')
train

,순위,영화명,개봉일,매출액,매출액 점유율,매출액증감 (전일대비),매출액증감율 (전일대비),누적매출액,관객수,관객수증감 (전일대비),...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
1,일별 박스오피스 검색 리스트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,순위,영화명,개봉일,매출액,매출액,매출액증감,매출액증감율,누적매출액,관객수,관객수증감,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
3,NaN,NaN,NaN,NaN,점유율,(전일대비),(전일대비),NaN,NaN,(전일대비),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,명량,2014-07-30 00:00:00,4892511700,0.595,-380933700,-0.1,61033902816,652776,-50111,...,1239,6776,한국,한국,(주)빅스톤픽쳐스,씨제이이앤엠(주),15세이상관람가,"사극,액션",김한민,"최민식,류승룡,조진웅,김명곤,진구,이정현,권율,노민우,김태훈,이승준,오타니 료헤이,..."
5,2,해적: 바다로 간 산적,2014-08-06 00:00:00,1890503200,0.23,-130889400,-0.1,4137374300,254862,-18583,...,795,3932,한국,한국,(주)하리마오픽쳐스,롯데쇼핑㈜롯데엔터테인먼트,12세이상관람가,어드벤처,이석훈,"김남길,손예진,유해진,이경영,오달수,김태우,박철민,신정근,김원해,조달환,조희봉,정성..."
6,3,드래곤 길들이기 2,2014-07-23 00:00:00,437352300,0.053,-27892900,-0.1,19775433889,58182,-3510,...,423,1016,미국,미국,드림웍스 애니메이션,씨제이이앤엠(주),전체관람가,"애니메이션,액션,어드벤처",딘 데블로이스,"제이 바루첼,제라드 버틀러,케이트 블란쳇,아메리카 페레라"
7,4,가디언즈 오브 갤럭시,2014-07-31 00:00:00,347508400,0.042,-11947100,0,7187518884,39837,-1650,...,344,844,미국,미국,마블 스튜디오,소니픽쳐스릴리징월트디즈니스튜디오스코리아(주),12세이상관람가,"액션,어드벤처,SF",제임스 건,"크리스 프랫,조 샐다나,데이브 바티스타,빈 디젤,브래들리 쿠퍼"
8,5,명탐정 코난 : 이차원의 저격수,2014-08-06 00:00:00,262921800,0.032,103795200,0.7,433027400,38912,15264,...,261,514,일본,일본,TMS 엔터테인먼트,씨제이이앤엠(주),12세이상관람가,"애니메이션,스릴러,어드벤처",시즈노 코분,"타카야마 미나미, 히다카 노리코"
9,6,군도: 민란의 시대,2014-07-23 00:00:00,117147900,0.014,-22492000,-0.2,36269954124,15940,-3066,...,233,495,한국,한국,"(주)영화사 월광,(주)쇼박스",(주)쇼박스,15세이상관람가,"사극,액션",윤종빈,"하정우,강동원,최귀화,이성민,조진웅,마동석,윤지혜,정만식,김성균,김재영,주진모,이경..."
10,7,허큘리스,2014-08-06 00:00:00,84582000,0.01,-2266400,0,181126400,11522,-187,...,278,692,미국,미국,"Paramount Pictures, Metro-Goldwyn-Mayer (MGM)",워너브러더스 코리아(주),15세이상관람가,"액션,어드벤처",브렛 래트너,"드웨인 존슨,존 허트,이안 맥쉐인,조셉 파인즈,이리나 샤크,바바라 팔빈"
11,8,마담 프루스트의 비밀정원,2014-07-24 00:00:00,28236100,0.003,-1124700,0,493871942,3702,-185,...,46,119,프랑스,프랑스,클로드 오자르,찬란,전체관람가,드라마,실뱅 쇼메,"귀욤 고익스,앤 르니"
12,9,터키,2014-07-31 00:00:00,21254400,0.003,-11883800,-0.4,665969600,3231,-1691,...,54,68,미국,미국,NaN,롯데쇼핑㈜롯데엔터테인먼트,전체관람가,"애니메이션,코미디",지미 헤이워드,"우디 해럴슨,오웬 윌슨"
13,10,극장판 뛰뛰빵빵 구조대 미션: 둥둥이를 구하라!,2014-08-07 00:00:00,18220700,0.002,15047900,4.7,31529500,2671,2219,...,87,127,한국,한국,"(주)빅스크리에이티브,(주)디씨지플러스,차이나필름그룹",메가박스(주)플러스엠,전체관람가,애니메이션,방형우,"양정화,안영미,김서영,이용신"
14,11,비긴 어게인,2014-08-13 00:00:00,17206000,0.002,-17802000,-0.5,62323000,2285,-2091,...,11,11,미국,미국,"시카 픽처스, 엑스큐스 미디어, 라이키 스토리, 아파 프로덕션, 블랙 라벨 미디어",판씨네마(주),15세이상관람가,멜로/로맨스,존 카니,"키이라 나이틀리,마크 러팔로,애덤 리바인,헤일리 스테인펠드,제임스 코든,캐서린 키너"
15,12,유아 넥스트,2014-08-07 00:00:00,14337400,0.002,6201400,0.8,31609400,1822,805,...,78,118,미국,미국,"HanWay Films, Snoot Entertainment",㈜영화사 백두대간,청소년관람불가,"공포(호러),액션",아담 윈가드,"샤니 빈슨,AJ 보웬,조 스완버그,롭 모란"
16,13,비행기 2: 소방구조대,2014-08-13 00:00:00,13568000,0.002,9498000,2.3,17638000,1696,1289,...,6,6,미국,미국,"디즈니툰 스튜디오, 월트 디즈니 픽처스",소니픽쳐스릴리징월트디즈니스튜디오스코리아(주),전체관람가,"애니메이션,어드벤처,코미디",로버츠 개너웨이,"데인 쿡,에드 해리스,줄리 보웬"
17,14,삼총사 2014,2014-08-07 00:00:00,5152000,0.001,5152000,1,5152000,1315,1315,...,21,21,러시아,러시아,NaN,(주)소나무픽쳐스,15세이상관람가,어드벤처,세르게이 지노프,"파벨 바샤크,유리 추신"
18,15,동경가족,2014-07-31 00:00:00,8967600,0.001,738600,0.1,103427300,1247,97,...,35,50,일본,일본,쇼치쿠,오드,전체관람가,"가족,드라마",야마다 요지,"하시즈메 이사오,요시유키 카즈코,츠마부키 사토시,아오이 유우,니시무라 마사히코,나츠..."
19,16,어떤 만남,2014-07-31 00:00:00,7956400,0.001,-1846000,-0.2,125821500,1089,-218,...,29,43,프랑스,프랑스,NaN,(주)티캐스트콘텐츠허브,청소년관람불가,멜로/로맨스,리사 아주엘로스,"소피 마르소,프랑수아 클뤼제"
20,17,모스트 원티드 맨,2014-08-07 00:00:00,7452900,0.001,6848400,11.3,13461400,971,902,...,26,42,영국,"영국,미국,독일",NaN,"(주)드림웨스트픽쳐스,(주)인벤트스톤",청소년관람불가,"스릴러,드라마",안톤 코르빈,"필립 세이모어 호프만,레이첼 맥아담스,윌렘 데포,로빈 라이트"
21,18,터널 3D,2014-08-20 00:00:00,9472000,0.001,9472000,1,9472000,902,902,...,2,4,한국,한국,"(주)필마픽쳐스 ,(주)씨제이에스지 마당엔터테인먼트",(주)박수엔터테인먼트,15세이상관람가,"공포(호러),스릴러",박규택,"정유미,연우진,송재림,정시연,이태현,박지원,서종민,전수아,전우재,양영택,유세문,정원..."
22,19,떡,2014-08-06 00:00:00,3994000,0,3954000,98.9,4034000,841,831,...,21,21,한국,한국,(주)케이알씨지,(주)케이알씨지,청소년관람불가,"멜로/로맨스,드라마",이영인,"추선,김원"
23,20,빙봉협: 중생지문,2014-08-06 00:00:00,3959000,0,3919000,98,3999000,835,825,...,20,20,홍콩,홍콩,NaN,(주)팝엔터테인먼트,15세이상관람가,"액션,판타지,코미디",나영창,"견자단,황성의,임달화"
24,21,프란시스 하,2014-07-17 00:00:00,5113100,0.001,-3836400,-0.4,488738800,686,-515,...,33,40,미국,미국,NaN,그린나래미디어(주),15세이상관람가,"코미디,멜로/로맨스",노아 바움백,"그레타 거윅,믹키 섬너,그레이스 검머,아담 드라이버"
25,22,그 사람 추기경,2014-08-06 00:00:00,3740500,0,3382200,9.4,38487800,548,498,...,43,54,한국,한국,평화방송,(주)씨타마운틴픽쳐스,전체관람가,다큐멘터리,전성우,"김수환,김영균"
26,23,이십세기폭스코리아(주),NaN,978000,0,-340000,-0.3,3807000,489,-163,...,1,4,미국,미국,이십세기폭스필름코퍼레이션,이십세기폭스코리아(주),NaN,"드라마,뮤지컬",오토 프레밍거,"해리 벨라폰테,도로시 댄드리지,펄 베일리"
27,24,혹성탈출: 반격의 서막,2014-07-10 00:00:00,1967000,0,-908000,-0.3,31497944295,329,-58,...,6,8,미국,미국,이십세기폭스코리아(주),이십세기폭스코리아(주),12세이상관람가,"액션,드라마,SF,스릴러",맷 리브스,"앤디 서키스,게리 올드만,제이슨 클락"
28,25,매직 인 더 문라이트,2014-08-20 00:00:00,2608000,0,2608000,1,2608000,326,326,...,1,1,미국,미국,NaN,(주)인벤트스톤,12세이상관람가,"코미디,드라마,멜로/로맨스",우디 앨런,"콜린 퍼스,엠마 스톤"
29,26,그녀,2014-05-22 00:00:00,1771000,0,-338500,-0.2,2828259400,235,-50,...,8,10,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),청소년관람불가,"드라마,멜로/로맨스",스파이크 존즈,"호아킨 피닉스,스칼렛 요한슨,에이미 아담스,루니 마라"
30,27,뜨거운 양철 지붕 위의 고양이,NaN,437000,0,437000,1,9985000,217,217,...,1,4,미국,미국,NaN,NaN,NaN,드라마,리차드 브룩스,"엘리자베스 테일러,폴 뉴먼,벌 아이비스"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,42,산타바바라,2014-07-16 00:00:00,313000,0,-120000,-0.3,120034000,45,-16,...,3,7,한국,한국,(주)영화사 조제,(주)나이너스엔터테인먼트,15세이상관람가,"멜로/로맨스,드라마",조성규,"이상윤,윤진서,이솜,서범석,신동미,정미라,정여은,강유현,차수민,이덕화,이석현,이선영..."
494,43,초급 이태리어 강습,NaN,178000,0,178000,1,178000,35,35,...,1,1,덴마크,덴마크,NaN,NaN,NaN,"코미디,드라마,멜로/로맨스",론 쉐르픽,"안데르스 W. 베르텔센,아네테 스토벨바엑"
495,44,피해자들,2014-07-31 00:00:00,186000,0,10000,0.1,2288000,31,1,...,4,5,한국,한국,(주)노시스에프앤디,골든타이드픽처스(주),청소년관람불가,"미스터리,스릴러",노진수,"류태준,장은아,연송하,송찬호,이가영,이상훈,이승현,이원기,이은주,김주애,김진휘,김진..."
496,45,커피 한잔이 섹스에 미치는 영향,2014-06-26 00:00:00,175000,0,88000,1,25468000,28,17,...,1,1,미국,미국,NaN,㈜영화사 백두대간,청소년관람불가,드라마,스테이시 패숀,"매기 시프,로빈 웨이거트"
497,46,쇼 미 러브,NaN,128000,0,128000,1,128000,26,26,...,1,1,스웨덴,스웨덴,NaN,NaN,NaN,멜로/로맨스,루카스 무디슨,"알렉산드라 달스트롬,레베카 릴예베르그,에리카 칼슨"
498,46,님포매니악 볼륨1,2014-06-18 00:00:00,252000,0,-23000,-0.1,475166883,26,-5,...,3,3,덴마크,"덴마크,독일,프랑스,벨기에,영국",NaN,CGV아트하우스,청소년관람불가,드라마,라스 폰 트리에,"샤를로뜨 갱스부르,스텔란 스카스가드,스테이시 마틴,샤이아 라보프,크리스찬 슬레이터,..."
499,46,랄프 스테드먼 스토리: 이상한 나라의 친구들,2014-07-10 00:00:00,131000,0,42000,0.5,29831800,26,8,...,2,2,영국,"영국,미국",NaN,㈜인디스토리,12세이상관람가,다큐멘터리,찰리 폴,"랄프 스테드먼,조니 뎁"
500,49,살인의 추억,2003-04-25 00:00:00,122997,0,122997,1,448497,24,24,...,1,1,한국,한국,(주)싸이더스,씨제이엔터테인먼트,15세관람가,스릴러,봉준호,"송강호,김상경,김뢰하,정인선,한충환,김효성,이강산,김민철,최현기,심성보,김희진,한성..."
501,49,파라노말 액티비티,2010-01-13 00:00:00,122997,0,122997,1,3209614497,24,24,...,1,1,미국,미국,브름하우스 프로덕션,(주)넥스트엔터테인먼트월드(NEW),12세이상관람가,"공포(호러),미스터리,스릴러",오렌 펠리,"케이티 피더스턴,미카 슬로앳,마크 프레드릭스"
502,51,미션 임파서블,1996-06-15 00:00:00,136000,0,136000,1,331000,21,21,...,1,1,미국,미국,파라마운트 픽쳐스,NaN,고등학생이상관람가,"액션,어드벤처,미스터리",브라이언 드 팔마,"톰 크루즈,존 보이트,엠마누엘 베아르,장 르노"
503,52,마음의 고향,NaN,92000,0,92000,1,92000,19,19,...,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,53,우리가족,2014-07-24 00:00:00,108000,0,-357000,-0.8,1870000,18,-57,...,6,9,한국,한국,NaN,(주)씨타마운틴픽쳐스,전체관람가,다큐멘터리,김도현,"김태훈,박은영,강민석,박진우,이희정,염하룡,이성태,이승환,이원영,이은정,김민석,김소..."
505,54,베르테르,2014-07-12 00:00:00,310000,0,212500,2.2,15126000,17,13,...,1,1,미국,미국,NaN,(주)인스터피씨엠,전체관람가,공연,리처드 이어,NaN
506,55,블랙딜,2014-07-03 00:00:00,94000,0,14000,0.2,58717200,15,5,...,2,3,한국,한국,(주)인디플러그,(주)인디플러그,12세이상관람가,다큐멘터리,이훈규,정태춘
507,56,끝까지 간다,2014-05-29 00:00:00,66000,0,49000,2.9,27002629900,11,8,...,1,1,한국,한국,"(주)에이디사공육,(주)다세포클럽",(주)쇼박스,15세이상관람가,"액션,스릴러,범죄",김성훈,"이선균,조진웅,신정근,정만식,신동미,김동영,박보검,박진성,정하철,윤종현,이승준,이준..."
508,57,짓: 무삭제 감독판,NaN,40000,0,40000,1,40000,10,10,...,1,1,한국,한국,㈜리필름,(주)팝엔터테인먼트,청소년관람불가,"멜로/로맨스,드라마",한종훈,"서태화,서은아"
509,58,머나먼 세상속으로,2014-07-31 00:00:00,41000,0,-87000,-0.7,2825000,7,-15,...,2,3,프랑스,"프랑스,벨기에,캐나다",NaN,(주)씨타마운틴픽쳐스,전체관람가,애니메이션,장 크리스토프 드상,"장 르노,로란트 도이취,이자벨 까레"
510,58,"자, 이제 댄스타임",2014-06-26 00:00:00,49000,0,49000,1,7853500,7,7,...,1,1,한국,한국,NaN,주식회사 키노엔터테인먼트,15세이상관람가,다큐멘터리,조세영,"박지혜,송삼동,지주현"
511,58,천번의 굿나잇,2014-07-03 00:00:00,56000,0,-322000,-0.9,73322000,7,-37,...,1,1,노르웨이,"노르웨이,아일랜드,스웨덴",NaN,(주)마인스 엔터테인먼트,12세이상관람가,드라마,에릭 포페,"줄리엣 비노쉬,니콜라이 코스터 왈도"
512,61,한공주,2014-04-17 00:00:00,29000,0,29000,1,1784429300,6,6,...,1,1,한국,한국,리 공동체 영화사,CGV아트하우스,청소년관람불가,드라마,이수진,"천우희,우혜진,정인선,김소영,강대현,백지원,임동석,장순호,전준영,정한빈,이상헌,이슬..."
513,61,와즈다,2014-06-19 00:00:00,48000,0,16000,0.5,78503200,6,2,...,1,1,기타,"기타,독일",NaN,(주)프레인글로벌,전체관람가,드라마,하이파 알-만수르,와드 모하메드
514,63,경주,2014-06-12 00:00:00,11000,0,-48000,-0.8,468281000,2,-7,...,1,1,한국,한국,"(주)인벤트스톤,률필름",(주)인벤트스톤,15세이상관람가,"드라마,코미디,멜로/로맨스",장률,"박해일,신민아,김태훈,신소율,이춘연,이학민,박재웅,박재희,박진홍,임상묵,임진욱,신민..."
515,63,카토 프로젝트,2014-04-17 00:00:00,4000,0,0,0,1323000,2,0,...,1,2,한국,한국,(주)씨타마운틴픽쳐스,(주)씨타마운틴픽쳐스,전체관람가,다큐멘터리,김정욱,"강민지,박정원,이승희,이윤희,이은지,이준영,김효정,박수정"
516,63,울프 앳 더 도어,2014-07-10 00:00:00,14000,0,14000,1,3149000,2,2,...,1,1,브라질,브라질,NaN,㈜영화사 백두대간,청소년관람불가,드라마,페르난도 코임브라,"린드라 릴,밀헴 코타즈,파비울라 나쉬멘토"
517,63,천하무적 키코리키,2014-07-17 00:00:00,12000,0,12000,1,149187900,2,2,...,1,1,러시아,러시아,NaN,와이드 릴리즈(주),전체관람가,"애니메이션,어드벤처",데니스 체르노프,NaN
518,67,언더 더 스킨,2014-07-17 00:00:00,7000,0,7000,1,13994000,1,1,...,1,1,영국,영국,NaN,씨네그루(주)다우기술,청소년관람불가,"SF,드라마",조나단 글레이저,"스칼렛 요한슨,폴 프래니건"
519,67,카프리치오,2014-07-05 00:00:00,30000,0,-190500,-0.9,10319500,1,-8,...,1,1,독일,독일,NaN,(주)쓰리캣프로덕션,전체관람가,공연,마르코 아르투로 마렐리,르네 플레밍
520,67,정동진독립영화제2013 섹션5,NaN,4000,0,4000,1,4000,1,1,...,1,1,한국,한국,NaN,NaN,NaN,기타,"유혜지,이미랑,송윤희,이진우",NaN
521,67,원나잇 온리,2014-07-03 00:00:00,7000,0,-136000,-1,21461300,1,-23,...,1,1,한국,한국,(주)레인보우팩토리,(주)레인보우팩토리,청소년관람불가,기타,김조광수,"유민규,박수진,장유상,정원조,김대준,김민기,조복래"
522,합계,NaN,NaN,10807003325,NaN,NaN,NaN,219275618399,1351842,NaN,...,3854,15093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
train.dtypes

순위               object
영화명              object
개봉일              object
매출액              object
매출액 점유율          object
매출액증감 (전일대비)     object
매출액증감율 (전일대비)    object
누적매출액            object
관객수              object
관객수증감 (전일대비)     object
관객수증감율 (전일대비)    object
누적관객수            object
스크린수             object
상영횟수             object
대표국적             object
국적               object
제작사              object
배급사              object
등급               object
장르               object
감독               object
배우               object
dtype: object

## Test - Split and extract dates

In [8]:
# train['순위'] = train['순위'].astype(str)

In [9]:
# train['순위'] = train['순위'].apply(lambda x: x.split(' '))
# train.loc[train['순위'].str[0]=='2014년']

## Insert Dates column

In [10]:
train.loc[train['순위']=='합계'].index.values

array([ 69, 151, 234, 304, 373, 445, 522], dtype=int64)

In [11]:
train.insert(0, '날짜', '2014년')
train.head(3)

,날짜,순위,영화명,개봉일,매출액,매출액 점유율,매출액증감 (전일대비),매출액증감율 (전일대비),누적매출액,관객수,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
1,2014년,일별 박스오피스 검색 리스트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014년,순위,영화명,개봉일,매출액,매출액,매출액증감,매출액증감율,누적매출액,관객수,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
3,2014년,NaN,NaN,NaN,NaN,점유율,(전일대비),(전일대비),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
train.loc[0:69, '날짜'] = '2014-08-07-목'
train.loc[70:151, '날짜'] = '2014-08-06-수'
train.loc[152:234, '날짜'] = '2014-08-05-화'
train.loc[235:304, '날짜'] = '2014-08-04-월'
train.loc[305:373, '날짜'] = '2014-08-03-일'
train.loc[374:445, '날짜'] = '2014-08-02-토'
train.loc[446:522, '날짜'] = '2014-08-01-금'

train.head(3)

,날짜,순위,영화명,개봉일,매출액,매출액 점유율,매출액증감 (전일대비),매출액증감율 (전일대비),누적매출액,관객수,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
1,2014-08-07-목,일별 박스오피스 검색 리스트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-08-07-목,순위,영화명,개봉일,매출액,매출액,매출액증감,매출액증감율,누적매출액,관객수,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
3,2014-08-07-목,NaN,NaN,NaN,NaN,점유율,(전일대비),(전일대비),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
train.loc[train['순위']=='일별 박스오피스 검색 리스트'].index.values[0]

1

In [14]:
# train.drop(train['순위']=='순위')
# train.drop(train['순위']=='합계')
train = train.drop(train.loc[train['순위']=='일별 박스오피스 검색 리스트'].index.values[0:])
train = train.drop(train.loc[train['순위']=='순위'].index.values[0:])
train = train.drop(train.loc[train['순위']=='합계'].index.values[0:])
train = train.drop(train.loc[train['매출액 점유율']=='점유율 '].index.values[0:])

train.head(3)

,날짜,순위,영화명,개봉일,매출액,매출액 점유율,매출액증감 (전일대비),매출액증감율 (전일대비),누적매출액,관객수,...,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
4,2014-08-07-목,1,명량,2014-07-30 00:00:00,4892511700,0.595,-380933700,-0.1,61033902816,652776,...,1239,6776,한국,한국,(주)빅스톤픽쳐스,씨제이이앤엠(주),15세이상관람가,"사극,액션",김한민,"최민식,류승룡,조진웅,김명곤,진구,이정현,권율,노민우,김태훈,이승준,오타니 료헤이,..."
5,2014-08-07-목,2,해적: 바다로 간 산적,2014-08-06 00:00:00,1890503200,0.23,-130889400,-0.1,4137374300,254862,...,795,3932,한국,한국,(주)하리마오픽쳐스,롯데쇼핑㈜롯데엔터테인먼트,12세이상관람가,어드벤처,이석훈,"김남길,손예진,유해진,이경영,오달수,김태우,박철민,신정근,김원해,조달환,조희봉,정성..."
6,2014-08-07-목,3,드래곤 길들이기 2,2014-07-23 00:00:00,437352300,0.053,-27892900,-0.1,19775433889,58182,...,423,1016,미국,미국,드림웍스 애니메이션,씨제이이앤엠(주),전체관람가,"애니메이션,액션,어드벤처",딘 데블로이스,"제이 바루첼,제라드 버틀러,케이트 블란쳇,아메리카 페레라"

In [15]:
# train[0:(train.loc[train['순위'].str[0]=='합계'].index.values[0])]
# train.dropna(subset='순위')

In [16]:
# train['날짜'] = train[0:(train.loc[train['순위'].str[0]=='합계'].index.values[0])]

In [17]:
# train['순위'] = train_df['순위'].apply(lambda x: clean_file(x))

## Output

In [18]:
train.to_csv(new_filename)


---
# Reset index  - junwoo -

In [55]:
#train = train.reset_index() # 전체 엑셀파일 데이터 다 모으고 하면됌
#train = train.drop('index',axis=1)

# Find NaN data and delete row

In [50]:
train.info() # 보니깐 482개중에 6개가 중간에 끼인 날짜정보칸임 476개만 진짜

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 24 columns):
level_0          482 non-null int64
날짜               482 non-null object
순위               482 non-null object
영화명              476 non-null object
개봉일              428 non-null object
매출액              476 non-null object
매출액 점유율          476 non-null object
매출액증감 (전일대비)     476 non-null object
매출액증감율 (전일대비)    476 non-null object
누적매출액            476 non-null object
관객수              476 non-null object
관객수증감 (전일대비)     476 non-null object
관객수증감율 (전일대비)    476 non-null object
누적관객수            476 non-null object
스크린수             476 non-null object
상영횟수             476 non-null object
대표국적             473 non-null object
국적               473 non-null object
제작사              167 non-null object
배급사              408 non-null object
등급               437 non-null object
장르               473 non-null object
감독               463 non-null object
배우               425 non-null object
dtypes: int64(1), object(23)
memory usage: 90.5+ KB

In [51]:
index=pd.isnull(train['영화명'])
for i in range(1,len(index)):
    if index[i]==True :
        print (i)

65
141
218
282
345
411

In [52]:
train.ix[282]

level_0                       282
날짜                   2014-08-03-일
순위               2014년 08월 03일(일)
영화명                           NaN
개봉일                           NaN
매출액                           NaN
매출액 점유율                       NaN
매출액증감 (전일대비)                  NaN
매출액증감율 (전일대비)                 NaN
누적매출액                         NaN
관객수                           NaN
관객수증감 (전일대비)                  NaN
관객수증감율 (전일대비)                 NaN
누적관객수                         NaN
스크린수                          NaN
상영횟수                          NaN
대표국적                          NaN
국적                            NaN
제작사                           NaN
배급사                           NaN
등급                            NaN
장르                            NaN
감독                            NaN
배우                            NaN
Name: 282, dtype: object

In [54]:
train = train.dropna(thresh=10) # NAN값이 10개 이상인 row 삭제
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476 entries, 0 to 481
Data columns (total 24 columns):
level_0          476 non-null int64
날짜               476 non-null object
순위               476 non-null object
영화명              476 non-null object
개봉일              428 non-null object
매출액              476 non-null object
매출액 점유율          476 non-null object
매출액증감 (전일대비)     476 non-null object
매출액증감율 (전일대비)    476 non-null object
누적매출액            476 non-null object
관객수              476 non-null object
관객수증감 (전일대비)     476 non-null object
관객수증감율 (전일대비)    476 non-null object
누적관객수            476 non-null object
스크린수             476 non-null object
상영횟수             476 non-null object
대표국적             473 non-null object
국적               473 non-null object
제작사              167 non-null object
배급사              408 non-null object
등급               437 non-null object
장르               473 non-null object
감독               463 non-null object
배우               425 non-null object
dtypes: int64(1), object(23)
memory usage: 93.0+ KB

# NaN Data
 - 개봉일 - 전부 합치고 가장 처음등장한 날짜를 개봉일로 채워주면 될듯 
 - 대표국적 -
 - 국적 - 
 - 제작사 - 
 - 배급사 - 
 - 등급 - 
 - 장르 - 
 - 감독 -
 - 배우 - (나머진 고민좀 해봐야할듯)